version: "3.9"

services:
  shop:
    build:
      context: .
      dockerfile: ./docker-files/Dockerfile
    environment:
      CONFIG: ProductionConfig
      SQLALCHEMY_DATABASE_URI: postgresql+pg8000://shop:shop@pg:5432/shop
    ports:
      - "8000:80"
    depends_on:
      pg:
        condition: service_healthy
  pg:
    image: postgres
    environment:
      POSTGRES_DB: shop
      POSTGRES_USER: shop
      POSTGRES_PASSWORD: shop
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - shop-pg-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  shop-pg-data:
